# Pre-commit hooks configuration
# Para usar este arquivo:
# 1. pip install pre-commit
# 2. pre-commit install
# 3. Os hooks serão executados automaticamente antes de cada commit

repos:
  # Hooks gerais para formatação e linting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  # Black - formatação de código Python
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3

  # isort - ordenação de imports
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # flake8 - linting
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=88', '--extend-ignore=E203,W503']

  # Django-specific checks
  - repo: local
    hooks:
      - id: django-check
        name: Django Check
        entry: python manage.py check
        language: system
        files: \.(py)$
        pass_filenames: false
        
      - id: django-test
        name: Django Tests
        entry: python manage.py test tarefas
        language: system
        files: \.(py)$
        pass_filenames: false
