name: Run Django Server on PR

on:
  pull_request:
    branches:
      - main

jobs:
  runserver:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda and activate environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-activate-base: false
        environment-file: environment.yml
        activate-environment: task-manager-env
        python-version: 3.12

    - name: Set SECRET_KEY env var
      run: echo "SECRET_KEY=teste-secreto-para-ci" >> $GITHUB_ENV

    - name: Run Django dev server
      run: |
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000 --noreload &
        sleep 10
        curl -f http://127.0.0.1:8000 || exit 1
      shell: bash -l {0}
